// SPDX-License-Identifier: AGPL-3.0-or-later
// Interface text. Rule and violation sentences come from @shiftknit/core (same wording as
// the CLI). Both catalogues must have the same keys (test/strings.test.ts).

import type { Lang } from '@shiftknit/core';

const en = {
  'app.tagline': 'Free, offline staff rota builder. Every rota is checked rule by rule.',
  'app.skip': 'Skip to the rota',
  'settings.lang': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.large': 'Large text',
  'setup.title': '1. Set up',
  'setup.project': 'Project',
  'setup.name': 'Project name',
  'setup.tz': 'Time zone (IANA)',
  'setup.start': 'First day',
  'setup.days': 'Number of days (1–31)',
  'setup.rest': 'Minimum rest between shifts (hours)',
  'setup.restDay': 'Rest-day rule: at least 1 rest day (24 hours off in a row) in every 7 days',
  'setup.restMode': 'Count rest days in',
  'setup.restMode.rolling': 'any 7 days in a row (stricter)',
  'setup.restMode.fixed': 'fixed 7-day blocks from the first day',
  'setup.restDayNote':
    'This preset follows the Labour Department’s Concise Guide to the Employment Ordinance (chapter 4, rest days). It is not legal advice: check your own obligations.',
  'setup.skills': 'Skills (comma separated)',
  'setup.new': 'New project',
  'setup.sample': 'Load sample',
  'setup.import': 'Open project file (.json)',
  'setup.delete': 'Delete all data on this device',
  'setup.deleteConfirm': 'Delete the project, rota and settings stored in this browser?',
  'setup.errors': 'Please fix these before scheduling:',
  'setup.imported': 'Project file opened.',
  'setup.importFailed': 'Could not open the file:',
  'shifts.title': 'Shifts',
  'shifts.name': 'Name',
  'shifts.start': 'Start',
  'shifts.end': 'End',
  'shifts.break': 'Unpaid break (min)',
  'shifts.demand': 'Staff needed',
  'shifts.skill': 'Must include',
  'shifts.skillNone': '(no skill need)',
  'shifts.skillMin': 'at least',
  'shifts.add': 'Add shift',
  'shifts.remove': 'Remove shift {name}',
  'shifts.overnight': 'ends next day',
  'staff.title': 'Staff',
  'staff.name': 'Name or code',
  'staff.skills': 'Skills',
  'staff.maxH': 'Max hours / week',
  'staff.minH': 'Min hours / week',
  'staff.maxC': 'Max days in a row',
  'staff.leave': 'Leave dates (YYYY-MM-DD, comma separated)',
  'staff.avoid': 'Prefers not to work on',
  'staff.add': 'Add person',
  'staff.remove': 'Remove {name}',
  'staff.more':
    'Availability windows and other preferences are kept; edit them in the project file.',
  'rota.title': '2. Rota',
  'rota.timeLimit': 'Time limit',
  'rota.solve': 'Make rota',
  'rota.stop': 'Stop',
  'rota.clear': 'Clear rota',
  'rota.unlock': 'Unlock all',
  'rota.solving': 'Working… you can keep using the page.',
  'rota.stopped': 'Stopped.',
  'rota.none': 'No rota yet. Press “Make rota”.',
  'rota.viewGrid': 'Staff × days',
  'rota.viewWeek': 'Week calendar',
  'rota.off': '—',
  'rota.lock': 'Lock',
  'rota.locked': 'Locked',
  'rota.cellLabel': '{name}, {date}',
  'rota.lockLabel': 'Lock {name} on {date}',
  'rota.short': 'short {n}',
  'rota.week': 'Week of {date}',
  'status.provenComplete':
    'Proven best: every staffing need is met and no better rota exists under your rules.',
  'status.complete':
    'Feasible (not proven best): every staffing need is met; the search stopped before it could prove this is the best.',
  'status.provenShortfall':
    'Proven best possible, but {n} staffing places cannot be filled under your rules.',
  'status.shortfall': 'Best found (not proven): {n} staffing places are unfilled.',
  'status.coverageImpossible': 'Full staffing is proven impossible under your rules.',
  'status.provenNone': 'No solution: no rota can follow all of your hard rules.',
  'status.none': 'No rota found within the time limit.',
  'status.rejected':
    'Internal check failed: the rota did not pass the independent checker, so it is not shown. Please report this.',
  'status.edited': 'Edited by hand. The rota is re-checked after every change.',
  'status.penalty': 'Preference and fairness score: {n} (lower is better).',
  'explain.title': 'Why?',
  'explain.working': 'Looking for the smallest set of rules that conflict…',
  'explain.intro': 'These rules cannot all be met at once (from {date}, {days} days):',
  'explain.minimal': 'Dropping any one of them removes the conflict.',
  'explain.notMinimal': 'This set is proven to conflict but may not be the smallest.',
  'explain.notFound': 'No short explanation was found within the search limit.',
  'check.title': 'Rule check',
  'check.ok': 'All hard rules are met.',
  'check.violations': '{n} broken rules:',
  'check.gaps': 'Unfilled needs:',
  'check.noGaps': 'Every staffing need is met.',
  'check.note':
    '“Passes the check” only means the rota follows the rules you entered. It does not mean it complies with any law; employers must check that themselves.',
  'penalty.preference': 'Preferences',
  'penalty.fairHours': 'Hours spread',
  'penalty.fairWeekend': 'Weekend spread',
  'penalty.fairNight': 'Night spread',
  'penalty.stability': 'Changes from previous rota',
  'penalty.isolatedDayOff': 'Single days off between work days',
  'export.title': '3. Export and print',
  'export.csvGrid': 'CSV (staff × days)',
  'export.csvList': 'CSV (list with hours)',
  'export.csvGaps': 'CSV (unfilled needs)',
  'export.json': 'Project file (.json)',
  'export.rota': 'Rota (.json)',
  'export.icsFor': 'Calendar file for',
  'export.ics': 'Download .ics',
  'export.printTeam': 'Print team rota',
  'export.printStaff': 'Print one page per person',
  'export.printRest': 'Print rest-day roster',
  'export.needRota': 'Make or enter a rota first.',
  'print.restTitle': 'Rest-day roster',
  'print.restNote': 'Rest day = a whole calendar day with no work. Period {from} to {to}.',
  'print.restDays': 'Rest days',
  'print.date': 'Date',
  'print.generated': 'Made with ShiftKnit {version}',
  'footer.privacy': 'Your data stays in this browser. Nothing is uploaded.',
  'footer.disclaimer':
    'ShiftKnit checks your rota against the rules you set. It is not legal advice and does not certify compliance with any law, including the Hong Kong rest-day preset.',
  'footer.affiliation':
    'ShiftKnit is an independent open-source project and is not affiliated with any company or government body.',
  'footer.source': 'Source code',
  'footer.licence': 'Licence: AGPL-3.0-or-later',
  'footer.coffee': 'Buy me a coffee',
  'new.shift': 'Day',
  'new.person': 'Person {n}',
  'new.project': 'New rota',
  'backup.remind':
    'You have made many changes since your last backup. Browsers can clear saved data (for example when space runs low), so keep a copy as a file.',
  'backup.download': 'Download full backup',
  'backup.dismiss': 'Not now',
  'backup.done':
    'Backup downloaded. Keep the file somewhere safe; open it with "Open project file" to restore.',
  'storage.persisted':
    'Storage: this browser has agreed to keep your data (it will not clear it automatically). A backup file is still a good idea.',
  'storage.bestEffort':
    'Storage: the browser may clear saved data if space runs low or after a long time unused. Download a backup now and then.',
  'storage.unsupported':
    'Storage: this browser cannot promise to keep saved data. Download a backup after each change you want to keep.',
  'setup.restored': 'Backup restored: project, rota and {n} published versions.',
  'collect.title': 'Collect availability from staff (no server)',
  'collect.intro':
    'Download the form and send it to your staff (for example in a chat app). Each person opens it, fills in when they can work, and sends you back the reply. Paste or open the replies here: you see every change and decide what to apply.',
  'collect.form': 'Download availability form',
  'collect.files': 'Open reply files',
  'collect.paste': 'Or paste replies here (several at once is fine)',
  'collect.read': 'Check replies',
  'collect.none': 'No replies found.',
  'collect.failed': 'Could not read the replies:',
  'collect.from': 'Reply from {name}',
  'collect.same': 'No changes: this matches what is already set.',
  'collect.apply': 'Apply',
  'collect.applyAll': 'Apply all',
  'collect.applied': 'Applied to {name}.',
  'collect.field.leave': 'Leave',
  'collect.field.avoid': 'Prefers not to work',
  'collect.field.note': 'Note',
  'avail.title': 'Availability and preferences',
  'avail.person': 'Person',
  'avail.any': 'Any time',
  'avail.off': 'Not available',
  'avail.between': 'Only between',
  'avail.several': 'Several time windows are set for this day; changing it here keeps only one.',
  'avail.prefs': 'Preferences',
  'avail.kind.want': 'Wants to work',
  'avail.kind.avoid': 'Prefers not to work',
  'avail.anyShift': 'any shift',
  'avail.everyDay': 'every day',
  'avail.weight': 'Strength (1–5)',
  'avail.addPref': 'Add preference',
  'avail.removePref': 'Remove preference {n}',
  'avail.noPrefs': 'No preferences.',
  'avail.when': 'Day',
  'avail.shift': 'Shift',
  'avail.kind': 'Type',
  'rota.next': 'Copy to next period',
  'rota.nextDone':
    'Moved to the next period ({date}) and copied the rota there as a draft. Re-check it: leave and availability may differ.',
  'hours.title': 'Weekly hours',
  'hours.person': 'Person',
  'hours.week': 'Week from {date}',
  'hours.total': 'Total',
  'hours.shifts': 'Shifts',
  'hours.none': 'Hours appear here once there is a rota.',
  'export.csvHours': 'Hours CSV',
  'export.share': 'Share file (.html, read-only)',
  'publish.title': '4. Publish and share',
  'publish.intro':
    'Publishing saves a numbered copy of the rota in this browser. Later versions list exactly who changed on which day. Send the share file (one HTML page, works offline, no account) to your team. Withdrawing a version cannot delete copies you have already sent: send the new share file instead.',
  'publish.publish': 'Publish this rota',
  'publish.withdraw': 'Withdraw the latest version',
  'publish.changesCsv': 'Changes CSV',
  'publish.versions': 'Published versions',
  'publish.none': 'Nothing published yet.',
  'publish.version': 'Version {n} · {at}',
  'publish.withdrawn': '(withdrawn)',
  'publish.current': '(current)',
  'publish.share': 'Share file',
  'publish.pending': 'Changes since version {n}: {count}',
  'publish.pendingNone': 'No changes since version {n}.',
  'publish.first': 'Not published yet: the first published version has no change list.',
  'publish.done': 'Published version {n}.',
  'publish.confirmBroken': 'This rota breaks {n} rules. Publish it anyway?',
  'publish.confirmWithdraw': 'Withdraw version {n}? It stays in the list, marked as withdrawn.',
  'publish.withdrawnDone': 'Version {n} withdrawn.',
  'publish.more': '… and {n} more (see the changes CSV).',
};

type Catalogue = Record<keyof typeof en, string>;

const zh: Catalogue = {
  'app.tagline': '免費、離線的排更工具。每份更表都逐條規則檢查。',
  'app.skip': '跳到更表',
  'settings.lang': '語言',
  'settings.theme': '外觀',
  'settings.theme.system': '跟系統',
  'settings.theme.light': '淺色',
  'settings.theme.dark': '深色',
  'settings.large': '大字',
  'setup.title': '1. 設定',
  'setup.project': '項目',
  'setup.name': '項目名稱',
  'setup.tz': '時區（IANA）',
  'setup.start': '第一日',
  'setup.days': '日數（1–31）',
  'setup.rest': '兩更之間最少休息（小時）',
  'setup.restDay': '休息日規則：每 7 日最少 1 個休息日（連續 24 小時不用工作）',
  'setup.restMode': '休息日計算方式',
  'setup.restMode.rolling': '任何連續 7 日（較嚴格）',
  'setup.restMode.fixed': '由第一日起每 7 日為一期',
  'setup.restDayNote':
    '此預設依照勞工處《僱傭條例簡明指南》第四章（休息日）設定，並非法律意見，請自行確認你的責任。',
  'setup.skills': '技能（以逗號分隔）',
  'setup.new': '新項目',
  'setup.sample': '載入示例',
  'setup.import': '開啟項目檔（.json）',
  'setup.delete': '刪除此裝置上的所有資料',
  'setup.deleteConfirm': '刪除儲存在此瀏覽器的項目、更表及設定？',
  'setup.errors': '排更前請先修正：',
  'setup.imported': '已開啟項目檔。',
  'setup.importFailed': '無法開啟檔案：',
  'shifts.title': '更份',
  'shifts.name': '名稱',
  'shifts.start': '開始',
  'shifts.end': '結束',
  'shifts.break': '無薪休息（分鐘）',
  'shifts.demand': '需要人數',
  'shifts.skill': '必須包括',
  'shifts.skillNone': '（無技能要求）',
  'shifts.skillMin': '最少',
  'shifts.add': '新增更份',
  'shifts.remove': '移除更份 {name}',
  'shifts.overnight': '翌日結束',
  'staff.title': '員工',
  'staff.name': '名稱或代號',
  'staff.skills': '技能',
  'staff.maxH': '每週最多工時',
  'staff.minH': '每週最少工時',
  'staff.maxC': '最多連續工作日',
  'staff.leave': '請假日期（YYYY-MM-DD，以逗號分隔）',
  'staff.avoid': '希望不用上班的日子',
  'staff.add': '新增員工',
  'staff.remove': '移除 {name}',
  'staff.more': '可工作時段及其他偏好會保留，可在項目檔內修改。',
  'rota.title': '2. 更表',
  'rota.timeLimit': '時間上限',
  'rota.solve': '自動排更',
  'rota.stop': '停止',
  'rota.clear': '清除更表',
  'rota.unlock': '全部解鎖',
  'rota.solving': '計算中……你可以繼續使用此頁。',
  'rota.stopped': '已停止。',
  'rota.none': '未有更表，請按「自動排更」。',
  'rota.viewGrid': '員工 × 日子',
  'rota.viewWeek': '週曆',
  'rota.off': '—',
  'rota.lock': '鎖定',
  'rota.locked': '已鎖定',
  'rota.cellLabel': '{name}，{date}',
  'rota.lockLabel': '鎖定 {name} 於 {date}',
  'rota.short': '欠 {n} 人',
  'rota.week': '{date} 起一週',
  'status.provenComplete': '已證明最佳：所有人手需求都已滿足，在你的規則下沒有更好的更表。',
  'status.complete': '可行（未證明最佳）：所有人手需求都已滿足；搜尋在證明最佳之前已停止。',
  'status.provenShortfall': '已證明是最佳可能，但在你的規則下有 {n} 個人手位無法填補。',
  'status.shortfall': '目前最佳（未證明）：仍有 {n} 個人手位未填補。',
  'status.coverageImpossible': '已證明在你的規則下無法滿足全部人手需求。',
  'status.provenNone': '無解：沒有更表能同時符合你所有硬性規則。',
  'status.none': '在時間上限內找不到更表。',
  'status.rejected': '內部檢查失敗：更表未能通過獨立檢查器，所以不會顯示。請回報此問題。',
  'status.edited': '已手動修改。每次修改後都會重新檢查。',
  'status.penalty': '偏好及公平分數：{n}（越低越好）。',
  'explain.title': '原因',
  'explain.working': '正在找出互相衝突的最少規則……',
  'explain.intro': '以下規則無法同時滿足（由 {date} 起 {days} 日）：',
  'explain.minimal': '去掉其中任何一條，衝突就會消失。',
  'explain.notMinimal': '已證明這組規則有衝突，但未必是最少的一組。',
  'explain.notFound': '在搜尋上限內找不到簡短的解釋。',
  'check.title': '規則檢查',
  'check.ok': '所有硬性規則都已符合。',
  'check.violations': '{n} 項違反規則：',
  'check.gaps': '未填補的需求：',
  'check.noGaps': '所有人手需求都已滿足。',
  'check.note':
    '「通過檢查」只代表更表符合你自己設定的規則，並不代表符合任何法例；僱主仍須自行確認。',
  'penalty.preference': '偏好',
  'penalty.fairHours': '工時差距',
  'penalty.fairWeekend': '週末差距',
  'penalty.fairNight': '夜更差距',
  'penalty.stability': '與上一期更表的改動',
  'penalty.isolatedDayOff': '工作日之間只休一日',
  'export.title': '3. 匯出及列印',
  'export.csvGrid': 'CSV（員工 × 日子）',
  'export.csvList': 'CSV（清單連工時）',
  'export.csvGaps': 'CSV（未填補需求）',
  'export.json': '項目檔（.json）',
  'export.rota': '更表（.json）',
  'export.icsFor': '日曆檔：',
  'export.ics': '下載 .ics',
  'export.printTeam': '列印全隊更表',
  'export.printStaff': '列印每人一頁',
  'export.printRest': '列印休息日更表',
  'export.needRota': '請先排更或輸入更表。',
  'print.restTitle': '休息日更表',
  'print.restNote': '休息日＝整個日曆日不用工作。期間：{from} 至 {to}。',
  'print.restDays': '休息日',
  'print.date': '日期',
  'print.generated': '由排更易 ShiftKnit {version} 製作',
  'footer.privacy': '你的資料只會留在此瀏覽器，不會上載。',
  'footer.disclaimer':
    '排更易只會按你設定的規則檢查更表，並非法律意見，亦不證明符合任何法例（包括香港休息日預設）。',
  'footer.affiliation': '排更易是獨立的開源項目，與任何公司或政府機構並無關連。',
  'footer.source': '原始碼',
  'footer.licence': '授權：AGPL-3.0-or-later',
  'footer.coffee': '請我飲杯咖啡',
  'new.shift': '日更',
  'new.person': '員工 {n}',
  'new.project': '新更表',
  'backup.remind':
    '自上次備份後你已作出多次改動。瀏覽器有機會清除已儲存的資料（例如空間不足時），請另存一份檔案。',
  'backup.download': '下載完整備份',
  'backup.dismiss': '稍後再說',
  'backup.done': '已下載備份。請妥善保存檔案；用「開啟項目檔」即可還原。',
  'storage.persisted': '儲存：此瀏覽器已同意保留你的資料（不會自動清除）。仍建議定期下載備份。',
  'storage.bestEffort':
    '儲存：空間不足或長時間未使用時，瀏覽器有機會清除已儲存的資料。請不時下載備份。',
  'storage.unsupported': '儲存：此瀏覽器無法保證保留資料。每次有想保留的改動後，請下載備份。',
  'setup.restored': '已還原備份：項目、更表及 {n} 個已發佈版本。',
  'collect.title': '向員工收集可工作時間（不經伺服器）',
  'collect.intro':
    '下載收集表並傳給員工（例如用通訊程式）。每人開啟後填寫可以上班的時間，再把回覆交回給你。在此貼上或開啟回覆：你會看到每項改動，再自行決定是否套用。',
  'collect.form': '下載可工作時間收集表',
  'collect.files': '開啟回覆檔',
  'collect.paste': '或在此貼上回覆（可一次貼多份）',
  'collect.read': '檢查回覆',
  'collect.none': '找不到回覆。',
  'collect.failed': '無法讀取回覆：',
  'collect.from': '{name} 的回覆',
  'collect.same': '沒有改動：與現有設定相同。',
  'collect.apply': '套用',
  'collect.applyAll': '全部套用',
  'collect.applied': '已套用到 {name}。',
  'collect.field.leave': '假期',
  'collect.field.avoid': '希望不用上班',
  'collect.field.note': '備註',
  'avail.title': '可工作時間及偏好',
  'avail.person': '員工',
  'avail.any': '任何時間',
  'avail.off': '不能上班',
  'avail.between': '只限',
  'avail.several': '這一天設有多個時間段；在此修改只會保留一個。',
  'avail.prefs': '偏好',
  'avail.kind.want': '希望上班',
  'avail.kind.avoid': '希望不用上班',
  'avail.anyShift': '任何更份',
  'avail.everyDay': '每一天',
  'avail.weight': '強度（1–5）',
  'avail.addPref': '新增偏好',
  'avail.removePref': '刪除偏好 {n}',
  'avail.noPrefs': '沒有偏好。',
  'avail.when': '日子',
  'avail.shift': '更份',
  'avail.kind': '類型',
  'rota.next': '複製到下一期',
  'rota.nextDone':
    '已轉到下一期（{date}），並把更表複製過去作為草稿。請重新檢查：假期及可工作時間可能不同。',
  'hours.title': '每週工時',
  'hours.person': '員工',
  'hours.week': '{date} 起一週',
  'hours.total': '合計',
  'hours.shifts': '更數',
  'hours.none': '排好更表後，這裏會顯示工時。',
  'export.csvHours': '工時 CSV',
  'export.share': '分享檔（.html，唯讀）',
  'publish.title': '4. 發佈及分享',
  'publish.intro':
    '「發佈」會在此瀏覽器保存一份有編號的更表副本。之後的版本會準確列出誰在哪一天有改動。把分享檔（單一 HTML 頁面，可離線開啟，無需帳戶）傳給團隊。撤回版本無法刪除已經傳出的副本，請改為傳送新的分享檔。',
  'publish.publish': '發佈此更表',
  'publish.withdraw': '撤回最新版本',
  'publish.changesCsv': '改動 CSV',
  'publish.versions': '已發佈版本',
  'publish.none': '尚未發佈。',
  'publish.version': '第 {n} 版 · {at}',
  'publish.withdrawn': '（已撤回）',
  'publish.current': '（現行）',
  'publish.share': '分享檔',
  'publish.pending': '與第 {n} 版比較的改動：{count} 項',
  'publish.pendingNone': '與第 {n} 版比較沒有改動。',
  'publish.first': '尚未發佈：第一個發佈版本沒有改動清單。',
  'publish.done': '已發佈第 {n} 版。',
  'publish.confirmBroken': '此更表違反 {n} 項規則。仍要發佈嗎？',
  'publish.confirmWithdraw': '撤回第 {n} 版？它會留在清單中並標示為已撤回。',
  'publish.withdrawnDone': '已撤回第 {n} 版。',
  'publish.more': '……另有 {n} 項（見改動 CSV）。',
};

export const UI: Record<Lang, Catalogue> = { en, 'zh-HK': zh };
export type UiKey = keyof typeof en;

export function ui(lang: Lang, key: UiKey, params: Record<string, string | number> = {}): string {
  return UI[lang][key].replace(/\{(\w+)\}/g, (m, k: string) =>
    k in params ? String(params[k]) : m,
  );
}
