// SPDX-License-Identifier: AGPL-3.0-or-later
// Interface text. Rule and violation sentences come from @shiftknit/core (same wording as
// the CLI). Both catalogues must have the same keys (test/strings.test.ts).

import type { Lang } from '@shiftknit/core';

const en = {
  'app.tagline': 'Free, offline staff rota builder. Every rota is checked rule by rule.',
  'app.skip': 'Skip to the rota',
  'settings.lang': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.large': 'Large text',
  'setup.title': '1. Set up',
  'setup.project': 'Project',
  'setup.name': 'Project name',
  'setup.tz': 'Time zone (IANA)',
  'setup.start': 'First day',
  'setup.days': 'Number of days (1–31)',
  'setup.rest': 'Minimum rest between shifts (hours)',
  'setup.restDay': 'Rest-day rule: at least 1 rest day (24 hours off in a row) in every 7 days',
  'setup.restMode': 'Count rest days in',
  'setup.restMode.rolling': 'any 7 days in a row (stricter)',
  'setup.restMode.fixed': 'fixed 7-day blocks from the first day',
  'setup.restDayNote':
    'This preset follows the Labour Department’s Concise Guide to the Employment Ordinance (chapter 4, rest days). It is not legal advice: check your own obligations.',
  'setup.skills': 'Skills (comma separated)',
  'setup.new': 'New project',
  'setup.sample': 'Load sample',
  'setup.import': 'Open project file (.json)',
  'setup.delete': 'Delete all data on this device',
  'setup.deleteConfirm': 'Delete the project, rota and settings stored in this browser?',
  'setup.errors': 'Please fix these before scheduling:',
  'setup.imported': 'Project file opened.',
  'setup.importFailed': 'Could not open the file:',
  'shifts.title': 'Shifts',
  'shifts.name': 'Name',
  'shifts.start': 'Start',
  'shifts.end': 'End',
  'shifts.break': 'Unpaid break (min)',
  'shifts.demand': 'Staff needed',
  'shifts.skill': 'Must include',
  'shifts.skillNone': '(no skill need)',
  'shifts.skillMin': 'at least',
  'shifts.add': 'Add shift',
  'shifts.remove': 'Remove shift {name}',
  'shifts.overnight': 'ends next day',
  'staff.title': 'Staff',
  'staff.name': 'Name or code',
  'staff.skills': 'Skills',
  'staff.maxH': 'Max hours / week',
  'staff.minH': 'Min hours / week',
  'staff.maxC': 'Max days in a row',
  'staff.leave': 'Leave dates (YYYY-MM-DD, comma separated)',
  'staff.avoid': 'Prefers not to work on',
  'staff.add': 'Add person',
  'staff.remove': 'Remove {name}',
  'staff.more':
    'Availability windows and other preferences are kept; edit them in the project file.',
  'rota.title': '2. Rota',
  'rota.timeLimit': 'Time limit',
  'rota.solve': 'Make rota',
  'rota.stop': 'Stop',
  'rota.clear': 'Clear rota',
  'rota.unlock': 'Unlock all',
  'rota.solving': 'Working… you can keep using the page.',
  'rota.stopped': 'Stopped.',
  'rota.none': 'No rota yet. Press “Make rota”.',
  'rota.viewGrid': 'Staff × days',
  'rota.viewWeek': 'Week calendar',
  'rota.off': '—',
  'rota.lock': 'Lock',
  'rota.locked': 'Locked',
  'rota.cellLabel': '{name}, {date}',
  'rota.lockLabel': 'Lock {name} on {date}',
  'rota.short': 'short {n}',
  'rota.week': 'Week of {date}',
  'status.provenComplete':
    'Proven best: every staffing need is met and no better rota exists under your rules.',
  'status.complete':
    'Feasible (not proven best): every staffing need is met; the search stopped before it could prove this is the best.',
  'status.provenShortfall':
    'Proven best possible, but {n} staffing places cannot be filled under your rules.',
  'status.shortfall': 'Best found (not proven): {n} staffing places are unfilled.',
  'status.coverageImpossible': 'Full staffing is proven impossible under your rules.',
  'status.provenNone': 'No solution: no rota can follow all of your hard rules.',
  'status.none': 'No rota found within the time limit.',
  'status.rejected':
    'Internal check failed: the rota did not pass the independent checker, so it is not shown. Please report this.',
  'status.edited': 'Edited by hand. The rota is re-checked after every change.',
  'status.penalty': 'Preference and fairness score: {n} (lower is better).',
  'explain.title': 'Why?',
  'explain.working': 'Looking for the smallest set of rules that conflict…',
  'explain.intro': 'These rules cannot all be met at once (from {date}, {days} days):',
  'explain.minimal': 'Dropping any one of them removes the conflict.',
  'explain.notMinimal': 'This set is proven to conflict but may not be the smallest.',
  'explain.notFound': 'No short explanation was found within the search limit.',
  'check.title': 'Rule check',
  'check.ok': 'All hard rules are met.',
  'check.violations': '{n} broken rules:',
  'check.gaps': 'Unfilled needs:',
  'check.noGaps': 'Every staffing need is met.',
  'check.note':
    '“Passes the check” only means the rota follows the rules you entered. It does not mean it complies with any law; employers must check that themselves.',
  'penalty.preference': 'Preferences',
  'penalty.fairHours': 'Hours spread',
  'penalty.fairWeekend': 'Weekend spread',
  'penalty.fairNight': 'Night spread',
  'penalty.stability': 'Changes from previous rota',
  'penalty.isolatedDayOff': 'Single days off between work days',
  'export.title': '3. Export and print',
  'export.csvGrid': 'CSV (staff × days)',
  'export.csvList': 'CSV (list with hours)',
  'export.csvGaps': 'CSV (unfilled needs)',
  'export.json': 'Project file (.json)',
  'export.rota': 'Rota (.json)',
  'export.icsFor': 'Calendar file for',
  'export.ics': 'Download .ics',
  'export.printTeam': 'Print team rota',
  'export.printStaff': 'Print one page per person',
  'export.printRest': 'Print rest-day roster',
  'export.needRota': 'Make or enter a rota first.',
  'print.restTitle': 'Rest-day roster',
  'print.restNote': 'Rest day = a whole calendar day with no work. Period {from} to {to}.',
  'print.restDays': 'Rest days',
  'print.date': 'Date',
  'print.generated': 'Made with ShiftKnit {version}',
  'footer.privacy': 'Your data stays in this browser. Nothing is uploaded.',
  'footer.disclaimer':
    'ShiftKnit checks your rota against the rules you set. It is not legal advice and does not certify compliance with any law, including the Hong Kong rest-day preset.',
  'footer.affiliation':
    'ShiftKnit is an independent open-source project and is not affiliated with any company or government body.',
  'footer.source': 'Source code',
  'footer.licence': 'Licence: AGPL-3.0-or-later',
  'footer.coffee': 'Buy me a coffee',
  'new.shift': 'Day',
  'new.person': 'Person {n}',
  'new.project': 'New rota',
};

type Catalogue = Record<keyof typeof en, string>;

const zh: Catalogue = {
  'app.tagline': '免費、離線的排更工具。每份更表都逐條規則檢查。',
  'app.skip': '跳到更表',
  'settings.lang': '語言',
  'settings.theme': '外觀',
  'settings.theme.system': '跟系統',
  'settings.theme.light': '淺色',
  'settings.theme.dark': '深色',
  'settings.large': '大字',
  'setup.title': '1. 設定',
  'setup.project': '項目',
  'setup.name': '項目名稱',
  'setup.tz': '時區（IANA）',
  'setup.start': '第一日',
  'setup.days': '日數（1–31）',
  'setup.rest': '兩更之間最少休息（小時）',
  'setup.restDay': '休息日規則：每 7 日最少 1 個休息日（連續 24 小時不用工作）',
  'setup.restMode': '休息日計算方式',
  'setup.restMode.rolling': '任何連續 7 日（較嚴格）',
  'setup.restMode.fixed': '由第一日起每 7 日為一期',
  'setup.restDayNote':
    '此預設依照勞工處《僱傭條例簡明指南》第四章（休息日）設定，並非法律意見，請自行確認你的責任。',
  'setup.skills': '技能（以逗號分隔）',
  'setup.new': '新項目',
  'setup.sample': '載入示例',
  'setup.import': '開啟項目檔（.json）',
  'setup.delete': '刪除此裝置上的所有資料',
  'setup.deleteConfirm': '刪除儲存在此瀏覽器的項目、更表及設定？',
  'setup.errors': '排更前請先修正：',
  'setup.imported': '已開啟項目檔。',
  'setup.importFailed': '無法開啟檔案：',
  'shifts.title': '更份',
  'shifts.name': '名稱',
  'shifts.start': '開始',
  'shifts.end': '結束',
  'shifts.break': '無薪休息（分鐘）',
  'shifts.demand': '需要人數',
  'shifts.skill': '必須包括',
  'shifts.skillNone': '（無技能要求）',
  'shifts.skillMin': '最少',
  'shifts.add': '新增更份',
  'shifts.remove': '移除更份 {name}',
  'shifts.overnight': '翌日結束',
  'staff.title': '員工',
  'staff.name': '名稱或代號',
  'staff.skills': '技能',
  'staff.maxH': '每週最多工時',
  'staff.minH': '每週最少工時',
  'staff.maxC': '最多連續工作日',
  'staff.leave': '請假日期（YYYY-MM-DD，以逗號分隔）',
  'staff.avoid': '希望不用上班的日子',
  'staff.add': '新增員工',
  'staff.remove': '移除 {name}',
  'staff.more': '可工作時段及其他偏好會保留，可在項目檔內修改。',
  'rota.title': '2. 更表',
  'rota.timeLimit': '時間上限',
  'rota.solve': '自動排更',
  'rota.stop': '停止',
  'rota.clear': '清除更表',
  'rota.unlock': '全部解鎖',
  'rota.solving': '計算中……你可以繼續使用此頁。',
  'rota.stopped': '已停止。',
  'rota.none': '未有更表，請按「自動排更」。',
  'rota.viewGrid': '員工 × 日子',
  'rota.viewWeek': '週曆',
  'rota.off': '—',
  'rota.lock': '鎖定',
  'rota.locked': '已鎖定',
  'rota.cellLabel': '{name}，{date}',
  'rota.lockLabel': '鎖定 {name} 於 {date}',
  'rota.short': '欠 {n} 人',
  'rota.week': '{date} 起一週',
  'status.provenComplete': '已證明最佳：所有人手需求都已滿足，在你的規則下沒有更好的更表。',
  'status.complete': '可行（未證明最佳）：所有人手需求都已滿足；搜尋在證明最佳之前已停止。',
  'status.provenShortfall': '已證明是最佳可能，但在你的規則下有 {n} 個人手位無法填補。',
  'status.shortfall': '目前最佳（未證明）：仍有 {n} 個人手位未填補。',
  'status.coverageImpossible': '已證明在你的規則下無法滿足全部人手需求。',
  'status.provenNone': '無解：沒有更表能同時符合你所有硬性規則。',
  'status.none': '在時間上限內找不到更表。',
  'status.rejected': '內部檢查失敗：更表未能通過獨立檢查器，所以不會顯示。請回報此問題。',
  'status.edited': '已手動修改。每次修改後都會重新檢查。',
  'status.penalty': '偏好及公平分數：{n}（越低越好）。',
  'explain.title': '原因',
  'explain.working': '正在找出互相衝突的最少規則……',
  'explain.intro': '以下規則無法同時滿足（由 {date} 起 {days} 日）：',
  'explain.minimal': '去掉其中任何一條，衝突就會消失。',
  'explain.notMinimal': '已證明這組規則有衝突，但未必是最少的一組。',
  'explain.notFound': '在搜尋上限內找不到簡短的解釋。',
  'check.title': '規則檢查',
  'check.ok': '所有硬性規則都已符合。',
  'check.violations': '{n} 項違反規則：',
  'check.gaps': '未填補的需求：',
  'check.noGaps': '所有人手需求都已滿足。',
  'check.note':
    '「通過檢查」只代表更表符合你自己設定的規則，並不代表符合任何法例；僱主仍須自行確認。',
  'penalty.preference': '偏好',
  'penalty.fairHours': '工時差距',
  'penalty.fairWeekend': '週末差距',
  'penalty.fairNight': '夜更差距',
  'penalty.stability': '與上一期更表的改動',
  'penalty.isolatedDayOff': '工作日之間只休一日',
  'export.title': '3. 匯出及列印',
  'export.csvGrid': 'CSV（員工 × 日子）',
  'export.csvList': 'CSV（清單連工時）',
  'export.csvGaps': 'CSV（未填補需求）',
  'export.json': '項目檔（.json）',
  'export.rota': '更表（.json）',
  'export.icsFor': '日曆檔：',
  'export.ics': '下載 .ics',
  'export.printTeam': '列印全隊更表',
  'export.printStaff': '列印每人一頁',
  'export.printRest': '列印休息日更表',
  'export.needRota': '請先排更或輸入更表。',
  'print.restTitle': '休息日更表',
  'print.restNote': '休息日＝整個日曆日不用工作。期間：{from} 至 {to}。',
  'print.restDays': '休息日',
  'print.date': '日期',
  'print.generated': '由排更易 ShiftKnit {version} 製作',
  'footer.privacy': '你的資料只會留在此瀏覽器，不會上載。',
  'footer.disclaimer':
    '排更易只會按你設定的規則檢查更表，並非法律意見，亦不證明符合任何法例（包括香港休息日預設）。',
  'footer.affiliation': '排更易是獨立的開源項目，與任何公司或政府機構並無關連。',
  'footer.source': '原始碼',
  'footer.licence': '授權：AGPL-3.0-or-later',
  'footer.coffee': '請我飲杯咖啡',
  'new.shift': '日更',
  'new.person': '員工 {n}',
  'new.project': '新更表',
};

export const UI: Record<Lang, Catalogue> = { en, 'zh-HK': zh };
export type UiKey = keyof typeof en;

export function ui(lang: Lang, key: UiKey, params: Record<string, string | number> = {}): string {
  return UI[lang][key].replace(/\{(\w+)\}/g, (m, k: string) =>
    k in params ? String(params[k]) : m,
  );
}
